version: '3'

services:
  api-solid-pg:
    image: bitnami/postgresql
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=apisolid